repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
        exclude: 'migrations/.*'
    -   id: trailing-whitespace
        exclude: 'migrations/.*'
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        exclude: 'migrations/.*'
